# Generated by Django 4.2.7 on 2024-01-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_number', models.IntegerField()),
                ('pocket', models.IntegerField()),
                ('party', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('card2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='card.normalcoup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('pocket', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('normal_check', models.IntegerField()),
                ('card2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='card.normalcoup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
