# Generated by Django 4.2.7 on 2024-01-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plusplayer',
            name='lose',
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='card1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plusplayer',
            name='card1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plusplayer',
            name='is_lose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='normalplayer',
            name='card2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plusplayer',
            name='card2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
