# Generated by Django 4.2.7 on 2024-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_plusplayer_lose_normalplayer_card1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalplayer',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='normalplayer',
            name='normal_check',
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='is_lose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalplayer',
            name='is_normal',
            field=models.BooleanField(default=True),
        ),
    ]
