# Generated by Django 4.2.7 on 2024-01-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0004_alter_normalplayer_user_alter_plusplayer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=True)),
                ('card_storage', models.TextField(blank=True, default='{}', null=True)),
                ('players_gold_storage', models.TextField(blank=True, default='{}', null=True)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.plusplayer')),
            ],
        ),
        migrations.CreateModel(
            name='NormalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(default=True)),
                ('card_storage', models.TextField(blank=True, default='{}', null=True)),
                ('players_gold_storage', models.TextField(blank=True, default='{}', null=True)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.normalplayer')),
            ],
        ),
    ]
