# Generated by Django 4.2.7 on 2024-01-04 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallobby',
            name='end_lobby',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='normallobby',
            name='life_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='normallobby',
            name='players',
        ),
        migrations.CreateModel(
            name='PlusLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_lobby', models.BooleanField(default=False)),
                ('life_time', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AddField(
            model_name='normallobby',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
