# Generated by Django 4.2.7 on 2024-01-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_normallobby_end_lobby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normallobby',
            old_name='end_lobby',
            new_name='is_end',
        ),
        migrations.RenameField(
            model_name='pluslobby',
            old_name='end_lobby',
            new_name='is_end',
        ),
    ]
