# Generated by Django 4.2.7 on 2024-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_rename_end_lobby_normallobby_is_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normallobby',
            name='scoreboard',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pluslobby',
            name='scoreboard',
            field=models.TextField(blank=True),
        ),
    ]
